[TOC]


## 加载所需的包
```{r}
# 软件检测和安装
library(ggplot2)
library(dplyr)
library(tidyr)
library(gridExtra)
library(cowplot)
library(multcompView)
library(agricolae)
library(fs) # For creating directories


```

## 数据加载
```{r}
# 文件路径设置
vegan_file <- "C:/16S/result/alpha2/vegan.txt"
metadata_file <- "C:/16S/result/alpha2/metadata_less.txt"

# 数据读取
vegan_data <- read.table(vegan_file, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
metadata <- read.table(metadata_file, header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# print(vegan_data)
# print(metadata)

```    


## 数据整合,长矩阵转换
```{r}
# 根据SampleID合并数据
merged_data <- merge(vegan_data, metadata, by = "SampleID")

# log2转换
indices_to_transform <- c("richness", "chao1", "ACE", "shannon", "simpson", "invsimpson")
merged_data[indices_to_transform] <- log2(merged_data[indices_to_transform])
# print(merged_data)

# 转换为长矩阵
long_data <- merged_data %>%
  pivot_longer(cols = c("richness", "chao1", "ACE", "shannon", "simpson", "invsimpson"),
               names_to = "Index",
               values_to = "Value")

# Preview long format data
# print(long_data)

```    


## 显著性差异说明
```{r}
# 差异是否显著按照字母显示
get_significance_letters <- function(data, index_name, groups) {
  subset_data <- data %>% filter(Index == index_name, Group_dayE %in% groups)
  model <- aov(Value ~ Group_dayE, data = subset_data)
  HSD_test <- HSD.test(model, "Group_dayE", group = TRUE)
  letters <- HSD_test$groups$groups
  names(letters) <- rownames(HSD_test$groups)
  return(letters)
}

```    


## 箱线图绘制_pmp
```{r}

# 分组顺序pmp
group_dayE_order <- c("HSpre", "HSmed", "HSpost", "HGpre", "HEmed", "HEpost", 
                      "DSpre", "DSmed", "DSpost", "DGpre", "DEmed", "DEpost", 
                      "ISpre", "ISmed", "ISpost", "IGpre", "IEmed", "IEpost")

# 按照分组顺序排列
long_data$Group_dayE <- factor(long_data$Group_dayE, levels = group_dayE_order)

# 按照分组创建每个组单独的子图
plot_group <- function(index_name, groups, letters) {
  plot_data <- long_data %>% filter(Index == index_name, Group_dayE %in% groups)
  max_values <- tapply(plot_data$Value, plot_data$Group_dayE, max)
  label_data <- data.frame(Group_dayE = factor(groups, levels = groups), 
                           Value = max_values + 0.05 * max(max_values, na.rm = TRUE), 
                           label = letters[groups])
  
  p <- ggplot(plot_data, 
              aes(x = factor(Group_dayE, levels = groups), y = Value, fill = Group_dayE)) +
    geom_violin(alpha = 0.3, aes(color = Group_dayE)) +
    geom_boxplot(width = 0.2, outlier.shape = NA, aes(color = Group_dayE), fill = NA) +
    geom_jitter(width = 0.1, alpha = 0.5, aes(color = Group_dayE), size = 0.5) +
    labs(title = paste("Boxplot of", index_name, "by", paste(groups, collapse = ", ")), x = "Group_dayE", y = index_name) +
    theme_minimal(base_size = 6) +
    theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 6),
          axis.title = element_text(size = 6),
          plot.title = element_text(size = 6),
          panel.border = element_rect(color = "black", fill = NA, size = 0.5)) +
    guides(fill = "none", color = "none") +
    geom_text(data = label_data, aes(x = Group_dayE, y = Value, label = label, color = Group_dayE), vjust = -0.5, size = 2) +
    scale_color_manual(values = scales::hue_pal()(length(groups))) +
    theme(legend.position = "none")
  
  return(p)
}

# 图形文件储存路径
output_dir <- "C:/16S/result/alpha2/plot_pmp_new"
dir_create(output_dir)

# 指数列表
indices <- c("richness", "chao1", "ACE", "shannon", "simpson", "invsimpson")

# 子图排列样式
groups_list <- list(
  c("HSpre", "HSmed", "HSpost"),
  c("HGpre", "HEmed", "HEpost"),
  c("DSpre", "DSmed", "DSpost"),
  c("DGpre", "DEmed", "DEpost"),
  c("ISpre", "ISmed", "ISpost"),
  c("IGpre", "IEmed", "IEpost")
)

# 创建图形并保存图形
for (index in indices) {
  plots <- lapply(groups_list, function(groups) {
    letters <- get_significance_letters(long_data, index, groups)
    plot_group(index, groups, letters)
  })
  combined_plot <- do.call(grid.arrange, c(plots, ncol = 2, nrow = 3))
  
  # 展示最终的图形
  print(combined_plot)
  
  # 保存为PNG和PDF
  ggsave(file.path(output_dir, paste0("boxplot_", index, ".png")), plot = combined_plot, width = 15, height = 18, units = "cm")
  ggsave(file.path(output_dir, paste0("boxplot_", index, ".pdf")), plot = combined_plot, width = 15, height = 18, units = "cm")
}

```    
 


## 箱线图绘制_DHI
```{r}

## 分组顺序DHI
# Define the order of Group_dayE
group_dayE_order <- c("DSpre", "HSpre", "ISpre", "DGpre", "HGpre", "IGpre", 
                      "DSmed", "HSmed", "ISmed", "DEmed", "HEmed", "IEmed", 
                      "DSpost", "HSpost", "ISpost", "DEpost", "HEpost", "IEpost")

# Convert Group_dayE to factor with specified order
long_data$Group_dayE <- factor(long_data$Group_dayE, levels = group_dayE_order)



# Function to create individual plots for each group of Group_dayE
plot_group <- function(index_name, groups, letters) {
  plot_data <- long_data %>% filter(Index == index_name, Group_dayE %in% groups)
  max_values <- tapply(plot_data$Value, plot_data$Group_dayE, max)
  label_data <- data.frame(Group_dayE = factor(groups, levels = groups), 
                           Value = max_values + 0.05 * max(max_values, na.rm = TRUE), 
                           label = letters[groups])
  
  p <- ggplot(plot_data, 
              aes(x = factor(Group_dayE, levels = groups), y = Value, fill = Group_dayE)) +
    geom_violin(alpha = 0.3, aes(color = Group_dayE)) +
    geom_boxplot(width = 0.2, outlier.shape = NA, aes(color = Group_dayE), fill = NA) +
    geom_jitter(width = 0.1, alpha = 0.5, aes(color = Group_dayE), size = 0.5) +
    labs(title = paste("Boxplot of", index_name, "by", paste(groups, collapse = ", ")), x = "Group_dayE", y = index_name) +
    theme_minimal(base_size = 6) +
    theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 6),
          axis.title = element_text(size = 6),
          plot.title = element_text(size = 6),
          panel.border = element_rect(color = "black", fill = NA, size = 0.5)) +
    guides(fill = "none", color = "none") +
    geom_text(data = label_data, aes(x = Group_dayE, y = Value, label = label, color = Group_dayE), vjust = -0.5, size = 2) +
    scale_color_manual(values = scales::hue_pal()(length(groups))) +
    theme(legend.position = "none")
  
  return(p)
}

# Create directory for saving plots
output_dir <- "C:/16S/result/alpha2/plot_DHI_new"
dir_create(output_dir)

# List of indices
indices <- c("richness", "chao1", "ACE", "shannon", "simpson", "invsimpson")

# List of groups for the new arrangement
new_groups_list <- list(
  c("DSpre", "HSpre", "ISpre"),
  c("DGpre", "HGpre", "IGpre"),
  c("DSmed", "HSmed", "ISmed"),
  c("DEmed", "HEmed", "IEmed"),
  c("DSpost", "HSpost", "ISpost"),
  c("DEpost", "HEpost", "IEpost")
)

# Create and save plots for each index
for (index in indices) {
  plots <- lapply(new_groups_list, function(groups) {
    letters <- get_significance_letters(long_data, index, groups)
    plot_group(index, groups, letters)
  })
  combined_plot <- do.call(grid.arrange, c(plots, ncol = 2, nrow = 3))
  
  # Display combined plot
  print(combined_plot)
  
  # Save combined plot as PNG and PDF
  ggsave(file.path(output_dir, paste0("boxplot_", index, ".png")), plot = combined_plot, width = 15, height = 18, units = "cm")
  ggsave(file.path(output_dir, paste0("boxplot_", index, ".pdf")), plot = combined_plot, width = 15, height = 18, units = "cm")
}


```    
 
 
 
 
## 箱线图绘制_SE
```{r}
## 分组顺序SE
# Define the order of Group_dayE
group_dayE_order <- c("DSpre", "DGpre", "HSpre", "HGpre", "ISpre", "IGpre", 
                      "DSmed", "DEmed", "HSmed", "HEmed", "ISmed", "IEmed", 
                      "DSpost", "DEpost", "HSpost", "HEpost", "ISpost", "IEpost")

# Convert Group_dayE to factor with specified order
long_data$Group_dayE <- factor(long_data$Group_dayE, levels = group_dayE_order)



# Function to create individual plots for each group of Group_dayE
plot_group <- function(index_name, groups, letters) {
  plot_data <- long_data %>% filter(Index == index_name, Group_dayE %in% groups)
  max_values <- tapply(plot_data$Value, plot_data$Group_dayE, max)
  label_data <- data.frame(Group_dayE = factor(groups, levels = groups), 
                           Value = max_values + 0.05 * max(max_values, na.rm = TRUE), 
                           label = letters[groups])
  
  p <- ggplot(plot_data, 
              aes(x = factor(Group_dayE, levels = groups), y = Value, fill = Group_dayE)) +
    geom_violin(alpha = 0.3, aes(color = Group_dayE)) +
    geom_boxplot(width = 0.2, outlier.shape = NA, aes(color = Group_dayE), fill = NA) +
    geom_jitter(width = 0.1, alpha = 0.5, aes(color = Group_dayE), size = 0.5) +
    labs(title = paste("Boxplot of", index_name, "by", paste(groups, collapse = ", ")), x = "Group_dayE", y = index_name) +
    theme_minimal(base_size = 6) +
    theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 6),
          axis.title = element_text(size = 6),
          plot.title = element_text(size = 6),
          panel.border = element_rect(color = "black", fill = NA, size = 0.5)) +
    guides(fill = "none", color = "none") +
    geom_text(data = label_data, aes(x = Group_dayE, y = Value, label = label, color = Group_dayE), vjust = -0.5, size = 2) +
    scale_color_manual(values = scales::hue_pal()(length(groups))) +
    theme(legend.position = "none")
  
  return(p)
}

# Create directory for saving plots
output_dir <- "C:/16S/result/alpha2/plot_SE_new"
dir_create(output_dir)

# List of indices
indices <- c("richness", "chao1", "ACE", "shannon", "simpson", "invsimpson")

# List of groups for the new arrangement
new_groups_list <- list(
  c("DSpre", "DGpre"),
  c("HSpre", "HGpre"),
  c("ISpre", "IGpre"),
  c("DSmed", "DEmed"),
  c("HSmed", "HEmed"),
  c("ISmed", "IEmed"),
  c("DSpost", "DEpost"),
  c("HSpost", "HEpost"),
  c("ISpost", "IEpost")
)

# Create and save plots for each index
for (index in indices) {
  plots <- lapply(new_groups_list, function(groups) {
    letters <- get_significance_letters(long_data, index, groups)
    plot_group(index, groups, letters)
  })
  combined_plot <- do.call(grid.arrange, c(plots, ncol = 3, nrow = 3))
  
  # Display combined plot
  print(combined_plot)
  
  # Save combined plot as PNG and PDF
  ggsave(file.path(output_dir, paste0("boxplot_", index, ".png")), plot = combined_plot, width = 15, height = 15, units = "cm")
  ggsave(file.path(output_dir, paste0("boxplot_", index, ".pdf")), plot = combined_plot, width = 15, height = 15, units = "cm")
}


 
```    
 
 
 

 
 
 