[TOC]


## 加载所需的包
```{r}
# 软件检测和安装

library(ggplot2)
library(dplyr)
library(ggbreak)
library(grid) 


```

## 数据导入
```{r}
# 设置文件路径
metadata_file <- "C:/16S/result/metadata_DH.txt"
all_group_longformat_file <- "C:/16S/result/faprotax2/all_group_longformat.txt"

# 读取 metadata 
metadata <- read.table(metadata_file, header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# 读取 all_group_longformat
all_group_longformat <- read.table(all_group_longformat_file, header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# print(metadata)
# print(all_group_longformat)

```    

## 数据合并
```{r}
# Set file paths
# Merge data based on common identifier
merged_data <- merge(all_group_longformat, metadata, by.x = "group", by.y = "SampleID")
# 移除 NA 项
merged_data <- merged_data[!is.na(merged_data$variable), ]


```    

## 数据处理
```{r}
# 定义变量顺序
variable_order <- c("chemoheterotrophy", "fermentation", "animal_parasites_or_symbionts", "aerobic_chemoheterotrophy",
                    "nitrate_reduction", "aromatic_compound_degradation", "aliphatic_non_methane_hydrocarbon_degradation",
                    "hydrocarbon_degradation", "methanol_oxidation", "methylotrophy", "human_associated", "ureolysis",
                    "respiration_of_sulfur_compounds", "human_gut", "mammal_gut", "human_pathogens_all", "sulfate_respiration",
                    "sulfite_respiration", "sulfur_respiration", "dark_hydrogen_oxidation")
# print(merged_data)

# 仅保留 variable_order 中的变量
merged_data <- merged_data[merged_data$variable %in% variable_order, ]

# 计算均值
mean_data <- merged_data %>%
  group_by(variable, State) %>% # 按 variable 和 State 分组
  summarise(mean_value = mean(value, na.rm = TRUE)) # 计算均值，忽略 NA


# 确保变量顺序不变
mean_data$variable <- factor(mean_data$variable, levels = rev(variable_order)) # 逆转顺序

# 对均值进行标准化
# mean_data <- mean_data %>%
#   group_by(State) %>% # 按 State 分组
#   mutate(normalized_mean = mean_value / sum(mean_value, na.rm = TRUE)) # 归一化均值

### 全局归一化
# 计算全局总和
total_sum <- sum(mean_data$mean_value, na.rm = TRUE) # 全部 mean_value 的总和

# 进行全局标准化
mean_data <- mean_data %>%
  mutate(normalized_mean = mean_value / total_sum) # 全局归一化
###

# 打印标准化后的数据进行检查
print(mean_data)

# 导出归一化后的文件
# library(tidyr)
# wide_matrix <- mean_data %>%
#   select(variable, State, normalized_mean) %>% # 选择需要的列
#   pivot_wider(names_from = State, values_from = normalized_mean) # 转换为宽矩阵
# 
# # 打印宽矩阵
# print(wide_matrix)
# 
# # 导出为 CSV 文件
# write.csv(wide_matrix, "C:/16S/result/faprotax2/normalized_mean_data_wide.csv", row.names = FALSE)

# merged_data$variable <- factor(merged_data$variable, levels = rev(variable_order)) # 逆转顺序以确保从上到下的顺序
```    

## 图形绘制
```{r}
###
# 自定义配色  #CCEBC5    #B3CDE3
custom_colors <- c("D" = "#FBB4AE", "H" = "#B3CDE3")

## 图形绘制 - 均值柱状图
p_mean <- ggplot(mean_data, aes(x = normalized_mean, y = variable, fill = State)) +
  geom_bar(stat = "identity", position = "dodge") + # 绘制柱状图
  scale_fill_manual(values = custom_colors) + # 应用自定义配色
  labs(title = "Function relative abundance (%)") + # 设置标题
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 6, hjust = 1), # 设置字体大小为 6pt
    axis.text.x = element_text(size = 6), # 设置字体大小为 6pt
    plot.title = element_text(size = 10, hjust = 0.5), # 设置标题字体大小并居中
    panel.grid.major = element_blank(), # 移除主网格线
    panel.grid.minor = element_blank(), # 移除次网格线
    axis.line = element_line(color = "black"), # 添加坐标轴线
    axis.ticks = element_line(color = "black"), # 添加刻度线
    panel.background = element_blank(), # 移除背景
    axis.title.y = element_blank(), # 移除 y 轴标题
    axis.title.x = element_blank() # 移除 x 轴标题
  ) +
  scale_x_break(c(0.0003, 0.01), scales = 0.9) +
  scale_x_continuous(
    breaks = c(0,0.00005,0.0001,0.00015,0.0002,0.00025,0.0003, 0.01,0.05, 0.1, 0.15), # 设置刻度
    labels = c("0", "0.005","0.010","0.015", "0.020", "0.025","0.030", "1","5","10", "15"), # 设置刻度标签
    expand = c(0, 0), # 防止扩展坐标轴范围
    position = "top" # 将 x 轴放置在顶部
  )

print(p_mean)

###

# 导出文件
# Save the plot as a PNG file
ggsave("C:/16S/result/faprotax2/bar_plot_DH_only_new2.png", plot = p_mean, width = 6, height = 5)
# # # Save the plot as a PDF file
ggsave("C:/16S/result/faprotax2/bar_plot_DH_only_new2.pdf", plot = p_mean, width = 6, height = 5)

```    
 
 
 
 

 
 
 
 
 
 
 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 